---
# file: tasks/main.yml

- name: Gather package facts
  package_facts:
    manager: auto

- name: Install cockpit
  ansible.builtin.dnf:
    name: cockpit
    state: latest
  notify: Enable cockpit service

- name: Install optional packages
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: latest
  when: "{{ item.when }}"
  with_items:
    - { name: cockpit-pcp, when: "'pcp' in ansible_facts.packages" }
    - { name: cockpit-machines, when: "'libvirt' in ansible_facts.packages" }   
    - { name: cockpit-podman, when: "'podman' in ansible_facts.packages" }

- name: Manage cockpit firewall policy
  ansible.posix.firewalld:
    service: cockpit
    state: enabled
    immediate: true
    permanent: true